### ISSUE TITLE
百度云盘上面的seg_only.bin文件有问题

### ISSUE THREAD

**Issue by zexpp5** [yizhiru/thulac4j#4]
`Exception in thread "main" com.esotericsoftware.kryo.KryoException: java.util.zip.ZipException: incorrect header check
	at com.esotericsoftware.kryo.io.Input.fill(Input.java:166)
	at com.esotericsoftware.kryo.io.Input.require(Input.java:196)
	at com.esotericsoftware.kryo.io.Input.readVarInt(Input.java:373)
	at com.esotericsoftware.kryo.Kryo.readReferenceOrNull(Kryo.java:846)
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:707)
	at io.github.yizhiru.thulac4j.base.CwsModel.loadModel(CwsModel.java:38)
	at io.github.yizhiru.thulac4j.base.CwsModel.loadModel(CwsModel.java:32)
	at io.github.yizhiru.thulac4j.SegOnly.<init>(SegOnly.java:17)
	at com.youwin.App.fenci(App.java:44)
	at com.youwin.App.main(App.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.util.zip.ZipException: incorrect header check
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164)
	at com.esotericsoftware.kryo.io.Input.fill(Input.java:164)
	... 14 more
`

**Comment by yizhiru** [comment]
我下载models.zip压缩包后，解压出来后，加载seg_only.bin文件后分词是没问题的。你看是不是下载压缩包不全，或者解压出来的文件有损坏
