### ISSUE TITLE
Simplifier Bug ?

### ISSUE THREAD

**Issue by gembin** [yizhiru/thulac4j#9]
```java
Simplifier simplifier = new Simplifier();
String s = simplifier.t2s("世界商機大發現");
System.out.println(s);
```
1.  运行时报错
```java
Exception in thread "main" java.lang.IllegalArgumentException: URI is not hierarchical
	at java.io.File.<init>(File.java:418)
	at io.github.yizhiru.thulac4j.process.Simplifier.<init>(Simplifier.java:24)
	at rosa.text.test.Thul4jTest.main(Thul4jTest.java:23)
```
原因应是model已经包含在jar包里了

2. [Simplifier Line 27](https://github.com/yizhiru/thulac4j/blob/master/src/main/java/io/github/yizhiru/thulac4j/process/Simplifier.java#L27) 建议用`try-with-resources`
```java
try (FileChannel channel = FileChannel.open(file.toPath(), StandardOpenOption.READ)) {
    // ...
}
```

**Comment by yizhiru** [comment]
@gembin 已经修复了，在新版本 1.3.1

**Comment by gembin** [comment]
@yizhiru COOL!
